/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4/userguide/building_java_projects.html
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use Scala 2.13 in our library project
    implementation("org.scala-lang:scala-library:2.13.6")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Dependencies for CSV processing
    implementation("com.nrinaudo:kantan.csv_2.13:0.6.2")
    implementation("com.nrinaudo:kantan.csv-generic_2.13:0.6.2")
    implementation("com.chuusai:shapeless_2.13:2.3.7")

    // Lucene Dependencies
    implementation("org.apache.lucene:lucene-core:8.11.1")
    implementation("org.apache.lucene:lucene-analyzers-common:8.11.1")
    implementation("org.apache.lucene:lucene-queryparser:8.11.1")

    // Deep Learning
    implementation("org.deeplearning4j:deeplearning4j-core:1.0.0-M1")
    implementation("org.deeplearning4j:deeplearning4j-nlp:1.0.0-M1")
    implementation("org.nd4j:nd4j-native:1.0.0-M1")
    implementation("org.nd4j:nd4j-native-platform:1.0.0-M1")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit4 test framework
            useJUnit("4.13.2")

            dependencies {
                // Use Scalatest for testing our library
                implementation("org.scalatest:scalatest_2.13:3.2.10")
                implementation("org.scalatestplus:junit-4-13_2.13:3.2.2.0")
                // Need scala-xml at test runtime
                runtimeOnly("org.scala-lang.modules:scala-xml_2.13:1.2.0")
            }
        }
    }
}

application {
    // Define the main class for the application.
    mainClass.set("synonyms.App")
}
